language: erlang
notifications:
notifications:
  recipients:
    - stuart.coyle@gmail.com
otp_release:
  - 17.1

before_install:
   - git clone https://github.com/elixir-lang/elixir
   - git checkout 'v0.14.0'
   - make -C elixir
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"

before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, deps.compile, test"
